// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJc-vxvcn8STIVG7T5yx3-ZssSWYI4ag',
    appId: '1:906652008618:web:79c6aea698e359530790d3',
    messagingSenderId: '906652008618',
    projectId: 'chat-9e2ce',
    authDomain: 'chat-9e2ce.firebaseapp.com',
    storageBucket: 'chat-9e2ce.firebasestorage.app',
    measurementId: 'G-PNGPHDBZ6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZArEIEJsQSvZGqN7fNvkN_nyrMV0iTXc',
    appId: '1:906652008618:android:434babdde95e3f010790d3',
    messagingSenderId: '906652008618',
    projectId: 'chat-9e2ce',
    storageBucket: 'chat-9e2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CfiZdY8FhbJWvfoXOIOgPPLxhPX4_0M',
    appId: '1:906652008618:ios:0c2710adc56c4b7a0790d3',
    messagingSenderId: '906652008618',
    projectId: 'chat-9e2ce',
    storageBucket: 'chat-9e2ce.firebasestorage.app',
    iosBundleId: 'com.example.campNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8CfiZdY8FhbJWvfoXOIOgPPLxhPX4_0M',
    appId: '1:906652008618:ios:0c2710adc56c4b7a0790d3',
    messagingSenderId: '906652008618',
    projectId: 'chat-9e2ce',
    storageBucket: 'chat-9e2ce.firebasestorage.app',
    iosBundleId: 'com.example.campNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwJc-vxvcn8STIVG7T5yx3-ZssSWYI4ag',
    appId: '1:906652008618:web:bc63bf69fdd666eb0790d3',
    messagingSenderId: '906652008618',
    projectId: 'chat-9e2ce',
    authDomain: 'chat-9e2ce.firebaseapp.com',
    storageBucket: 'chat-9e2ce.firebasestorage.app',
    measurementId: 'G-FY7PM3CSXQ',
  );
}
